name: 'Setup Bot'
description: 'Common setup steps for bot scripts'
inputs:
    node-version:
        description: 'Node.js version'
        default: '22.x'
runs:
    using: 'composite'
    steps:
        - uses: pnpm/action-setup@v6
        - name: Set Node Version
          uses: actions/setup-node@v6
          with:
              node-version: ${{ inputs.node-version }}
              cache: pnpm
        - name: Install dependencies
          run: pnpm install --frozen-lockfile
          shell: bash
