name: 'Elaina daily'

on:
    schedule:
        - cron: '10 16 * * *' # 00:10 CST Everyday
    workflow_dispatch:
        inputs:
            task:
                description: '选择任务'
                type: choice
                required: true
                options:
                    - cleanSandbox

env:
    API_USER_AGENT: ${{ secrets.API_USER_AGENT }}
    MH_BOT: ${{ secrets.MH_BOT }}

jobs:
    cleanSandbox:
        if: |
            github.event.schedule == '10 16 * * *' ||
            github.event.inputs.task == 'cleanSandbox'
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/setup-bot
            - name: Run Script
              run: npx tsx src/bot/elaina/cleanSandbox.ts
