name: 'Manually'

on:
    workflow_dispatch:
        inputs:
            task:
                description: '选择任务'
                type: choice
                required: true
                options:
                    - linkModifier
                    - monthly

env:
    API_USER_AGENT: ${{ secrets.API_USER_AGENT }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    linkModifier:
        if: |
            github.event.inputs.task == 'linkModifier'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - name: Set Node Version
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: pnpm
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Run Script
              env:
                  ZH_BOT: ${{ secrets.ZH_BOT }}
              run: npx tsx src/bot/mgp/linkModifier.ts

    monthly:
        if: |
            github.event.inputs.task == 'monthly'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - name: Set Node Version
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: pnpm
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Run Script
              env:
                  ZH_BOT: ${{ secrets.ZH_BOT }}
              run: npx tsx src/bot/mgp/monthly.ts
