name: 'Manually'

on:
    workflow_dispatch:
        inputs:
            task:
                description: '选择任务'
                type: choice
                required: true
                options:
                    - linkModifier
                    - monthly

env:
    API_USER_AGENT: ${{ secrets.API_USER_AGENT }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    ZH_BOT: ${{ secrets.ZH_BOT }}

jobs:
    linkModifier:
        if: |
            github.event.inputs.task == 'linkModifier'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Setup Bot
              uses: ./.github/actions/setup-bot
              with:
                  node-version: '20.x'
            - name: Run Script
              run: npx tsx src/bot/mgp/linkModifier.ts

    monthly:
        if: |
            github.event.inputs.task == 'monthly'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Setup Bot
              uses: ./.github/actions/setup-bot
              with:
                  node-version: '20.x'
            - name: Run Script
              run: npx tsx src/bot/mgp/monthly.ts
