name: 'QW daily'

on:
    # schedule:
    #     - cron: '15 */3 * * *' # Every 3 hours (08:15 11:15 14:15 17:20 ... CST)
    workflow_dispatch:
        inputs:
            task:
                description: '选择任务'
                type: choice
                required: true
                options:
                    - internalLink

env:
    API_USER_AGENT: ${{ secrets.API_USER_AGENT }}
    QW_BOT: ${{ secrets.QW_BOT }}

jobs:
    internalLink:
        if: |
            github.event.inputs.task == 'internalLink'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - name: Set Node Version
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: pnpm
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Run Script
              run: npx tsx src/bot/qw/internalLink.ts
