name: 'QW daily'

on:
    # schedule:
    #     - cron: '15 */3 * * *' # Every 3 hours (08:15 11:15 14:15 17:20 ... CST)
    workflow_dispatch:
        inputs:
            task:
                description: '选择任务'
                type: choice
                required: true
                options:
                    - internalLink
                    - internalLink-exist
                    - nullEdit
            category:
                description: '分类'
                type: string
                required: false
                default: '有蓝链却未移除内部链接助手模板的页面'

env:
    API_USER_AGENT: ${{ secrets.API_USER_AGENT }}
    QW_BOT: ${{ secrets.QW_BOT }}

jobs:
    internalLink:
        if: |
            github.event.inputs.task == 'internalLink'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Setup Bot
              uses: ./.github/actions/setup-bot
            - name: Run Script
              run: npx tsx src/bot/qw/internalLink.ts

    internalLink-exist:
        if: |
            github.event.inputs.task == 'internalLink-exist'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Setup Bot
              uses: ./.github/actions/setup-bot
            - name: Run Script
              run: npx tsx src/bot/qw/internalLink-exist.ts

    nullEdit:
        if: |
            github.event.inputs.task == 'nullEdit'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Setup Bot
              uses: ./.github/actions/setup-bot
            - name: Run Script
              env:
                  CATEGORY: ${{ github.event.inputs.category }}
              run: npx tsx src/bot/qw/nullEdit.ts
